### ISSUE TITLE
[New] Some feature requirements

### ISSUE THREAD

**Issue by YKDZ** [Coll1234567/MineTweaks#2]
1. Right clicking a ladder with another one will place it in the next block .
2. Swing Through Grass
3. Note Blocks with heads attached to it can emit the respective mob's sound.
4. A Trowel like Quark

**Comment by Coll1234567** [comment]
Addressed in 929b181848aace5e9f7a496bf224e2c733bd8649:

1. Done
2. This would require a large rewrite of the combat system, which isn't feasible at this time.
3. Done
4. Done
