### ISSUE TITLE
Bonemealing Sand and Red Sand removes the item in creative.

### ISSUE THREAD

**Issue by VonSparq** [Coll1234567/MineTweaks#5]
Hi, I just noticed another minor issue which is probably really simple to fix by just checking for player's gamemode before removing the item.
The issue is with the Sand and Red Sand bonemealing to make it grow dead bushes tweak, it removes the bonemeal from player's inventory even when they are in creative, this is different to how bonemealing grass blocks works with the bonemeal staying in the creative player's inventory which makes bonemealing large areas faster.

**Comment by Coll1234567** [comment]
Fixed for 1.3.0.

**Comment by VonSparq** [comment]
> 
> 
> Fixed for 1.3.0.

Amazing! Thank you very much for making this amazing plugin and for quickly fixing any issues!
